[agent]
model = "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free"
parser = "openai/gpt-oss-120b:free"
vector = "nvidia/llama-nemotron-embed-vl-1b-v2:free"

[postgresql]
name = "nodepoint"
user = "nodepoint"
password = "nodepoint"
host = "localhost"
port = 5432

[mongo]
user = "admin"
password = "password"
host = "localhost"
port = 27017
database = "contentdb"
auth_source = "admin"

[redis]
host = "localhost"
port = 6379
db = 0

[quadrant]
host = "localhost"
port = 6333
collection_name = "nodepoint"
vector_size = 1024
