# Generated by Django 6.0.5 on 2026-05-15 09:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodepoint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('compressions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='nodepoint.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ChatBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_root', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='nodepoint.chatbranch')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='nodepoint.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool')], max_length=20)),
                ('content', models.TextField(blank=True, default='')),
                ('reasoning_content', models.TextField(blank=True, null=True)),
                ('tool_calls', models.JSONField(blank=True, null=True)),
                ('tool_call_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tool_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='nodepoint.chatbranch')),
            ],
            options={
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('branch', 'sequence'), name='unique_message_sequence_per_branch')],
            },
        ),
        migrations.AddConstraint(
            model_name='chatbranch',
            constraint=models.UniqueConstraint(condition=models.Q(('is_root', True)), fields=('conversation',), name='unique_root_branch_per_conversation'),
        ),
    ]
