# Generated by Django 6.0.5 on 2026-05-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodepoint', '0009_remove_workspace_is_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacegroup',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
