# Generated by Django 6.0.5 on 2026-05-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodepoint', '0010_workspacegroup_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacegroup',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
