# Generated by Django 6.0.5 on 2026-05-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodepoint', '0011_workspacegroup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workspace',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
