# Generated by Django 6.0.5 on 2026-05-30 06:00

import django.db.models.deletion
from django.db import migrations, models


def normalize_group_tags(apps, schema_editor):
    WorkspaceGroup = apps.get_model("nodepoint", "WorkspaceGroup")
    valid = {"workspace", "files", "entity", "relation"}
    for group in WorkspaceGroup.objects.all().only("id", "tag"):
        if group.tag not in valid:
            group.tag = "workspace"
            group.save(update_fields=["tag"])


class Migration(migrations.Migration):

    dependencies = [
        ('nodepoint', '0012_workspace_tag_description'),
    ]

    operations = [
        migrations.RunPython(normalize_group_tags, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='workspacegroup',
            name='tag',
            field=models.CharField(choices=[('workspace', 'Workspace'), ('files', 'Files'), ('entity', 'Entity'), ('relation', 'Relation')], default='workspace', max_length=16),
        ),
        migrations.CreateModel(
            name='GroupDocumentMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='nodepoint.document')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_memberships', to='nodepoint.workspacegroup')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('group', 'document'), name='unique_document_per_group')],
            },
        ),
        migrations.CreateModel(
            name='GroupEntityMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='nodepoint.knowledgeentity')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_memberships', to='nodepoint.workspacegroup')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('group', 'entity'), name='unique_entity_per_group')],
            },
        ),
        migrations.CreateModel(
            name='GroupRelationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_memberships', to='nodepoint.workspacegroup')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='nodepoint.knowledgerelation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('group', 'relation'), name='unique_relation_per_group')],
            },
        ),
    ]
