"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import sys

from nodepoint.settings_loader import postgres_config, redis_config
from nodepoint.registry.prompt import Prompt

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-yv6r(r4aruaityi#-stp%ahgu#^+a(6536_e*7zh(af52r5(5(",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").lower() in ("1", "true", "yes")

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "*").split(",")


# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels",
    "rest_framework",
    "django_rq",
    "nodepoint",
]

ASGI_APPLICATION = "config.asgi.application"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_pg = postgres_config()
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": _pg["NAME"],
        "USER": _pg["USER"],
        "PASSWORD": _pg["PASSWORD"],
        "HOST": _pg["HOST"],
        "PORT": _pg["PORT"],
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

_redis = redis_config()
# RQ worker default was 1800s; orchestrator batch-waits for chunk jobs need longer.
RQ_DEFAULT_JOB_TIMEOUT = int(os.getenv("RQ_DEFAULT_JOB_TIMEOUT", "10800"))
PREPROCESS_JOB_TIMEOUT = os.getenv("PREPROCESS_JOB_TIMEOUT", "3h")
_rq_queue = {**_redis, "DEFAULT_TIMEOUT": RQ_DEFAULT_JOB_TIMEOUT}
RQ_QUEUES = {
    "orchestrator": _rq_queue,
    "chunk": _rq_queue,
    "vector": _rq_queue,
    "high": _rq_queue,
    "default": _rq_queue,
    "low": _rq_queue,
}
RQ_QUEUE_ORCHESTRATOR = "orchestrator"
RQ_QUEUE_ORCHESTRATOR_HIGH = "high"
RQ_QUEUE_ORCHESTRATOR_LOW = "low"
RQ_QUEUE_CHUNK = "chunk"
RQ_QUEUE_VECTOR = "vector"
RQ = {
    "WORKER_CLASS": "nodepoint.workers.NodepointWorker",
}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                (
                    _redis["HOST"],
                    int(_redis["PORT"]),
                )
            ],
        },
    },
}

CHAT_COMPRESS_TOKEN_THRESHOLD = int(os.getenv("CHAT_COMPRESS_TOKEN_THRESHOLD", "80000"))
CHAT_COMPRESS_MAX_TOOL_CHARS = int(os.getenv("CHAT_COMPRESS_MAX_TOOL_CHARS", "4000"))
CHAT_COMPRESS_MAX_ASSISTANT_CHARS = int(
    os.getenv("CHAT_COMPRESS_MAX_ASSISTANT_CHARS", "8000")
)
CHAT_COMPRESS_MAX_MESSAGES = int(os.getenv("CHAT_COMPRESS_MAX_MESSAGES", "30"))
CHAT_COMPRESS_MAX_OUTPUT_TOKENS = int(
    os.getenv("CHAT_COMPRESS_MAX_OUTPUT_TOKENS", "4000")
)
CHAT_COMPRESS_TEMPERATURE = float(os.getenv("CHAT_COMPRESS_TEMPERATURE", "0.2"))
CHAT_COMPRESS_OMIT_REASONING = os.getenv("CHAT_COMPRESS_OMIT_REASONING", "true").lower() in (
    "1",
    "true",
    "yes",
    "on",
)
CHAT_DEFAULT_SYSTEM = os.getenv("CHAT_DEFAULT_SYSTEM", Prompt["chat_system"])
CHAT_MAX_CONCURRENT_SEARCHES = int(os.getenv("CHAT_MAX_CONCURRENT_SEARCHES", "8"))
CHAT_TURN_REDIS_TTL = int(os.getenv("CHAT_TURN_REDIS_TTL", "3600"))
WEB_WORKERS = int(os.getenv("WEB_WORKERS", "4"))
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO").upper()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(levelname)s %(asctime)s %(name)s %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django": {"level": "INFO", "propagate": True},
        "django.request": {"level": "WARNING", "propagate": True},
        "nodepoint": {"level": LOG_LEVEL, "propagate": True},
        "urllib3": {"level": "WARNING", "propagate": True},
    },
}

_db_conn_max_age = os.getenv("DB_CONN_MAX_AGE", "60")
DATABASES["default"]["CONN_MAX_AGE"] = int(_db_conn_max_age)

if "test" in sys.argv:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": ":memory:",
        }
    }
    CHANNEL_LAYERS = {
        "default": {"BACKEND": "channels.layers.InMemoryChannelLayer"},
    }